name = "junction"
compatibility_date = "2025-12-29"

main = "apps/frontend/.output/_worker.js"

[assets]
directory = "apps/frontend/.output"

[vars]
NUXT_PUBLIC_APP_NAME = "Junction"
HTTP_TYPE = "http"
SERVER_HOST = "backend.junct.dpdns.org"
BACKEND_PORT = "8080"
FRONTEND_PORT = "3000"
