name = "junction"
compatibility_date = "2025-12-29"

main = "apps/frontend/.output/_worker.js"

[assets]
directory = "apps/frontend/.output"

[vars]
NUXT_PUBLIC_APP_NAME = "Junction"
NUXT_PUBLIC_HTTP_TYPE = "http"
NUXT_PUBLIC_SERVER_HOST = "backend.junct.dpdns.org"
NUXT_PUBLIC_BACKEND_PORT = "8080"
NUXT_PUBLIC_FRONTEND_PORT = "3000"
